### ISSUE TITLE
The included gcc compiler is broken

### ISSUE THREAD

**Issue by LucaT1** [kissx/packages#19] opened 2019-07-10 16:06 UTC
it seems that the included GCC compiler does not properly work. I tried compiling linux(skipping the bootstrapping step at first) and got this error:
<details>
<summary>screenshot</summary>
<img src="https://user-images.githubusercontent.com/29304787/60984842-a4d07180-a33c-11e9-9db4-b5c42807f0cf.jpg">
</details>

After that, I tried bootstrapping the packages first, but it gave me an error right away when automake checks for a c99 compatible compiler(for which gcc returns false).

The last thing I tried was recompiling gcc itself via `kiss build gcc` but I also had no luck there. It returned the same `internal compiler error: Illegal instruction`. Do you guys run into the same problem or have any idea on how to fix this?

**Comment by konimex** [comment] 2019-07-10 16:07
Yes, it's a confirmed bug, I'm trying to work on it.

**Comment by dylanaraps** [comment] 2019-07-11 07:09
Building a new `chroot` as we speak.

**Comment by LucaT1** [comment] 2019-07-11 07:14
Sweet! Can't wait to try it out.

**Comment by konimex** [comment] 2019-07-11 08:47
Please try [0.0.9-musl](https://github.com/kissx/packages/releases/tag/0.0.9-musl).

The easiest package to test this with is `busybox` so you may want to start there.

**Comment by dylanaraps** [comment] 2019-07-11 08:48
It hasn't uploaded yet. It's almost done however.

**Comment by dylanaraps** [comment] 2019-07-11 08:58
Uploaded: https://github.com/kissx/packages/releases/tag/0.0.9-musl

**Comment by LucaT1** [comment] 2019-07-11 09:42
Just tried it again, but still doesn't seem to work. I'll provide some additional information about my setup here:
Running Alpine Linux live on bare metal
(don't think cpu specs/memory matter really)

The error is now different, the problem when building the kernel now seems to be with m4.
Here is the kernel build output:
<details>
  <summary>screenshot</summary>
  <img src="https://user-images.githubusercontent.com/29304787/61040108-46ed6980-a3d0-11e9-89c1-495afeb9346a.jpg">
</details>

I tried rebuilding the m4 utility but also had no luck there:
<details>
  <summary>screenshot</summary>
  <img src="https://user-images.githubusercontent.com/29304787/61040190-6be1dc80-a3d0-11e9-957c-e32109ab7e47.jpg">
</details>

I also tried `busybox` as suggested and gave one last shot at gcc but again, same errors about illegal instructions.

**Comment by LucaT1** [comment] 2019-07-12 09:50
Just tried with the latest build(`0.0.13`). Now it looks like the flex package is missing the `libintl` library, although the header file for libintl is available. Here are some outputs:

<details>
  <summary>$ kiss build linux</summary>
<pre><code>
/ # kiss build linux
=> Resolving dependencies...
=> Building: linux.
=> Continue?: [y/n].
y
=> Checking to see if any dependencies have already been built...
=> Installing any pre-built dependencies...
=> [linux]: Checking repository files...
=> [linux]: Downloading sources...
=> [linux]: Found cached source 'linux-5.1.16.tar.xz'.
=> [linux]: Found local file 'files/.config'.
=> [linux]: Generated/Verified checksums.
=> [linux]: Extracting sources...
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/confdata.o
  HOSTCC  scripts/kconfig/expr.o
  LEX     scripts/kconfig/lexer.lex.c
Error loading shared library libintl.so.8: No such file or directory (needed by /bin/flex)
make[2]: *** [scripts/Makefile.lib:194: scripts/kconfig/lexer.lex.c] Error 127
make[1]: *** [Makefile:552: syncconfig] Error 2
Makefile:639: include/config/auto.conf.cmd: No such file or directory
make: *** [Makefile:657: include/config/auto.conf.cmd] Error 2
!> [linux]: Build failed.
</code></pre>
</details>

Then I tried recompiling flex which seems to require calling flex itself(WTF) and then I did some research and found that the libintl module comes from gettext. So I rebuilt gettext and once again, broken gcc I'd say.
[gist](https://gist.github.com/LucaT1/c957483cb4c3bb190ced59b074d9cf45)

**Comment by dylanaraps** [comment] 2019-07-12 11:52
Yup. It’s still broken. We’re still trying to get GCC to compile generically. I’ll fix the flex error, thanks for picking up on that (this was caused by recreating the chroot from Void).

**Comment by dylanaraps** [comment] 2019-07-13 15:43
Try the latest `chroot`. The issue should be fixed.

https://github.com/kissx/packages/releases/tag/0.0.14-musl

**Comment by LucaT1** [comment] 2019-07-13 18:11
I'm currently building the kernel, and it's taking a fair while. But for now, all ok, I've gotten to the compilation of drivers which is (as I remember) one of the latest steps! So for now, all good.

**Comment by dylanaraps** [comment] 2019-07-14 06:59
Closing this as a further two people with the same issue have confirmed it is fixed. Will await your reply. Feel free to reopen this if the issue still occurs. :+1:

**Closed by dylanaraps** 2019-07-14 06:59 UTC
Labels: bug
